load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    hdrs = [
        "AdjacencyList.h",
        "AdjacencyMatrix.h",
        "Edge.h",
        "Graph.h",
        "TimeCounter.h",
        "Utils.h",
        "Vertex.h",
    ],
)
